### ISSUE TITLE
Error: can't find file 'spec_helper'

### ISSUE THREAD

**Issue by s0kil** [ilmanzo/crystal-koans#11]
Getting the error when trying to run `crystal run koans.cr`

It seems the `spec/spec_helper.cr` file was deleted in this commit: https://github.com/ilmanzo/crystal-koans/commit/7095033645c83034746f8e94ef6049e244770903

**Comment by ilmanzo** [comment]
whops, you're right; I moved it to "lib" but it was in gitignore; now should be fixed. Thanks for reporting!
