### ISSUE TITLE
Solution for nil_spec impossible?

### ISSUE THREAD

**Issue by matthewmcgarvey** [ilmanzo/crystal-koans#2]
Is there a solution for [this line in nil_spec](https://github.com/ilmanzo/crystal-koans/blob/master/spec/nil_spec.cr#L6)?  Whenever i try the solution `Nil.class.should eq Class` i get the error `can't use Class as generic type argument yet, use a more specific type`.  Did you have a different solution in mind?

**Comment by ilmanzo** [comment]
you're right, thanks for pointing it out. I made a quick fix, but if you have some suggestions would be great !
