### ISSUE TITLE
sync list of files

### ISSUE THREAD

**Issue by aeldemery** [ilmanzo/crystal-koans#20]
missing `yaml` and `type_reflection`

**Comment by ilmanzo** [comment]
Thanks, I left them out because not fully sure to be 'ready' . What do you think about the sequence of specs? Are them in the right order for a beginner?

**Comment by aeldemery** [comment]
Thanks for your efforts. perhaps the ones about bigint, bigdecimal, bittarray, levenstein could be moved at the end because they are rather specific. I wish there were more test to parse text and files specially in regex, xml.
