### ISSUE TITLE
Minor issue: Stack vs Queue on Generics Chapter

### ISSUE THREAD

**Issue by yvern** [ilmanzo/crystal-koans#23]
Firstly congrats on the awesome resource, it is very pleasurable to use and understand.

Apparently in the ´generics_spec.cr´, what we have is a Stack and not a Queue.

Expecting a FIFO behaviour and getting a LIFO one can mess a bit with learners (as me) heads.

Maybe change description to use Stack instead? or change implementation to match naming?

**Comment by ilmanzo** [comment]
good point, will have a look on that !
