### ISSUE TITLE
boolean_spec, Nil vs nil

### ISSUE THREAD

**Issue by pavloo** [ilmanzo/crystal-koans#3]
Hey, thanks for the project. It's fun, I'm a big fan of learning new languages via koans.
Quick question, is "Nil", not "nil", put intentionally here or it's a typo? It got me confused :)

https://github.com/ilmanzo/crystal-koans/blob/master/spec/booleans_spec.cr#L28

**Comment by ilmanzo** [comment]
hi, thanks for spotting it; initially I had the idea to show the difference between Nil and nil ; but since it's the first exercise maybe it's better to be plain and simple
